### ISSUE TITLE
Add /calendar command

### ISSUE THREAD

**Issue by albertopastormr** [SciDataUCM/koe-bot#1]
We use Google Calendar to organize all the events we host, [here is the link to our calendar](https://goo.gl/Jxg496). 
__/calendar__ should return a list of the upcoming events we're hosting.

**Comment by pkos98** [comment]
good evening, may I implement this command?
(If so, fyi: I would do it tomorrow)

**Comment by albertopastormr** [comment]
It's all yours !

**Comment by thepabloaguilar** [comment]
@albertopastormr Can I try for today? Because he will implement this tomorrow, I'm making the Scrap to catch.

**Comment by albertopastormr** [comment]
Let's give him the opportunity to propose his implementation. If you have any idea to extend this functionality with a brand new command, open an issue explaining it. 
I've just opened a new issue, take a look at it if you want to contribute :) #7
