### ISSUE TITLE
Add /pollution command

### ISSUE THREAD

**Issue by albertopastormr** [SciDataUCM/koe-bot#12]
Koe "lives" at University Complutense of Madrid, [here](https://goo.gl/maps/CbBbmZBptXv). We want Koe to tell about the pollution near the building, given that Google Maps location.
**Input:** `/pollution`
**Output:** `Current pollution  at the campus: <actual pollution information>`, for example.

**Comment by Andrey-Raspopov** [comment]
Good day! I'd like to help with this one for hacktoberfest and for the sake of your Uni's student's health!

Can you provide more information on the format of the message, which will be the most usefull? There are about 20 reads of CO and SO2, and 3 different reads of NO2, including stratosphere and troposphere.

I think ideal message should contain simple prognosis like one that Seattle or London services provide, what do you think?
