### ISSUE TITLE
Add /learn command

### ISSUE THREAD

**Issue by albertopastormr** [SciDataUCM/koe-bot#15]
We want Koe to be crucial helping others members learning required skills for data science/big data/AI. Therefore, we want Koe to provide useful links to free resources as courses, guides, GitHub repositories, etc.
**Input:** `/learn`
**Output:** `<list of formatted links with a brief description>`

**Comment by marciobbj** [comment]
I can try this one :)

**Comment by albertopastormr** [comment]
Sure :)

**Comment by ghost** [comment]
Feel free to roast me: https://github.com/SciDataUCM/koe-bot/pull/18
:D

**Comment by albertopastormr** [comment]
Thank you for your contribution !! :))
