### ISSUE TITLE
Add /membership command

### ISSUE THREAD

**Issue by albertopastormr** [SciDataUCM/koe-bot#2]
New members use Google Forms to register to the community.
Koe should be able to return [this link](https://goo.gl/forms/7Jwvm6istokrlOpx2) given the command __/membership__.

**Comment by pkos98** [comment]
good evening, may I implement this command?
(If so, fyi: I would do it tomorrow)

**Comment by albertopastormr** [comment]
Sure ! 👍

**Comment by albertopastormr** [comment]
Implemented at #10
