### ISSUE TITLE
credentials

### ISSUE THREAD

**Issue by dlgeraghty** [SciDataUCM/koe-bot#22]
lines 12 and 13 of koe.py:

BOTNAME = 'experiment'
TOKEN = '682028880:AAFSJjYfITyFUOAGqQVlYvCvUATJFgCd2os'

are wrong, these credentials correspond to an experimental bot, wich works fine, but it causes the koe bot to be unaccesable from telegram

**Comment by dlgeraghty** [comment]
in fact, these lines should be replaced with:

BOTNAME = 'KoeBot'
WEATHER_API_KEY = os.environ['WEATHER_API_KEY']

**Comment by albertopastormr** [comment]
Fixed in https://github.com/SciDataUCM/koe-bot/commit/8dbfdf3c240e160976582d6f86150ce6c5fc0fdf
