### ISSUE TITLE
Add /collaborate command

### ISSUE THREAD

**Issue by albertopastormr** [SciDataUCM/koe-bot#3]
SciDataUCM members use Google Forms to submit their ideas.
Koe should be able to return [this link](https://goo.gl/forms/zvpjNENtQk56WQSA2) given the command __/collaborate__.

**Comment by pegasus-lynx** [comment]
Can I work on this issue?? I wanted to know that, What do you mean by 'return' here? Or should the bot return the link in a message or should it open the link and take us to that link?

**Comment by albertopastormr** [comment]
Hi ! When I said 'return this link' I meant 'return the link in a message'. So if you input the command /collaborate, the bot should write a message (with a little bit of formatting, just some text to make it look 'human') linking to [this website](https://goo.gl/forms/zvpjNENtQk56WQSA2).
For example, it could be something like `Here you can find some information about collaborating with SciDataUCM` [link](https://goo.gl/forms/zvpjNENtQk56WQSA2).
I hope I solved your question ! 😃

**Comment by pegasus-lynx** [comment]
I got it. Thank You. I am on it.

**Comment by albertopastormr** [comment]
Implemented.
