### ISSUE TITLE
Add /weather command

### ISSUE THREAD

**Issue by albertopastormr** [SciDataUCM/koe-bot#7]
Koe "lives" at University Complutense of Madrid, [here](https://goo.gl/maps/AXwJWVMG9342). We want Koe to tell about the weather near the building, given that Google Maps location. 
__Input:__ `/weather`
__Output:__ `It's pretty cold/hot here at the campus ! <actual weather information>`, for example.

**Comment by thepabloaguilar** [comment]
I'll do this issue!!

**Comment by zilehuda** [comment]
I'll take this up. :)

**Comment by zilehuda** [comment]
Need config.txt file for TOKEN @albertopastormr

**Comment by thepabloaguilar** [comment]
@zilehuda I've made this.
